config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/about'
  get 'static_pages/faq'
  get 'static_pages/contact'

  resources :groups
  resources :events
  root 'events#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :group

  def group_name 
    group.try(:name);
  end

  def group_name=(name) 
    self.group = Group.find_or_create_by(name: name) if name.present?
  end
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def edit
    @event = Event.find(params[:id])
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to @event
    else
      render :new
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_url
  end

  private
    def event_params
      params.require(:event).permit(:title, :description, :cost, :email, :start, :end, :group_name)
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def new
  end

  def create
    group = Group.new
    group.name = params[:group][:name]
    group.save
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end

  def faq
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/events/_form.html.erb
<%= form_with scope: :event, url: events_path, local: true do |form| %>
  <%= form.label :title %></br>
  <%= form.text_field :title %></br>

  <%= form.label :cost %></br>
  $<%= form.number_field :cost %></br>

  <%= form.label :description%></br>
  <%= form.text_area :description %></br>

  <%= form.label :email %></br>
  <%= form.email_field :email %></br>

  <%= form.label :start %></br>
  <%= form.datetime_select :start %></br>

  <%= form.label :end %></br>
  <%= form.datetime_select :end %></br>

  <%= form.label :group_name %></br>
  <%= form.text_field :group_name, id: :event_group_name, data:{autocomplete_source: Group.order('LOWER(name)').map(&:name)} %>

  <p><%= form.submit %></p>

<% end %>

app/views/events/edit.html.erb
<h1> Edit Event </h1>
<%= button_to 'Delete', event_path(@event), method: :delete %>
<%= render 'form'%>

app/views/events/index.html.erb
<%= link_to 'New Event', new_event_path, class:"btn btn-default pull-right" %>

<table class="table">
  <tr> 
    <th>Title</th>
    <th>Description</th>
    <th>Cost</th>
    <th>Email</th>
    <th>Start</th>
    <th>End</th>
    <th>Group ID</th>
  </tr>
  <% @events.each do |event| %>
    <tr>
      <td><%= event.title %></td>
      <td><%= event.description %></td>
      <td><%= number_to_currency(event.cost) %></td>
      <td><%= mail_to event.email %></td>
      <td><%= event.start %></td>
      <td><%= event.end %></td>
      <% if event.group_id %>
        <td><%= Group.find(event.group_id).name %></td>
      <% else %>
        <td></td>
      <% end %>
      <td><%= link_to 'Show', event_path(event) %></td>
    </tr>
  <% end %>
</table>

app/views/events/new.html.erb
<h1> New Event </h1>
<%= render 'form'%>

app/views/events/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>
 
<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>
 
<p>
  <strong>Cost:</strong>
  <%= number_to_currency(@event.cost) %>
</p>
 
<p>
  <strong>Email:</strong>
  <%= mail_to @event.email %>
</p>
 
<p>
  <strong>Start:</strong>
  <%= @event.start %>
</p>
 
<p>
  <strong>End:</strong>
  <%= @event.end %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScoutShare</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'favicon.ico' %>
  </head>

  <body>
    <div class="header">
      <%= image_tag "tents-header.jpg", class:"img-responsive" %>
      <nav class="navbar navbar-inverse" >
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <div class="collapse navbar-collapse" id="navbar">
            <ul class="nav navbar-nav">
              <li>
                <%= link_to image_tag('logo/White.png') + "ScoutShare", root_path %>
              </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">About<span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "About", static_pages_about_path %></li>
                  <li><%= link_to "FAQ", static_pages_faq_path %></li>
                  <li><%= link_to "Contact", static_pages_contact_path %></li>
                </ul>
              </li>
              <li><a href="#">Login</a></li>
            </ul>
          </div>
        </div>
      </nav>
    </div>

    <div class="container-fluid" id = "body">
      <div class= "content well">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<h1>About</h1>

app/views/static_pages/contact.html.erb
<h1>Contact</h1>

app/views/static_pages/faq.html.erb
<h1>FAQ</h1>